CREATE TABLE [dbo].[Events]
(
  [Id] UNIQUEIDENTIFIER NOT NULL, 
  [BotId] UNIQUEIDENTIFIER NOT NULL, 
  [Type] NVARCHAR (50) NOT NULL,
  [Content] NVARCHAR (255) NOT NULL,
  [DateCreated] DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT [PK_events_event_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
)
